name: reporting
description: A starting point for Dart libraries or applications.
version: 1.1.0
homepage: https://github.com/jonasbadstuebner/reporting
publish_to: none

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  usage: ^4.1.1
  tool_base:
    git: https://github.com/graux/tool_base.git
    # path: /home/jbadstuebner/Dokumente/git/github.com/jonasbadstuebner/tool_base/main
  http: ^1.3.0

dev_dependencies:
  test: ^1.24.1
  mockito: ^5.4.0
  tool_base_test:
    git: https://github.com/graux/tool_base_test.git
    # path: /home/jbadstuebner/Dokumente/git/github.com/jonasbadstuebner/tool_base_test/main
  args: ^2.4.0
  quiver: ^3.2.1
  meta: ^1.9.1
